# Generated by Django 5.0 on 2023-12-13 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='copies',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
