# Generated by Django 5.0 on 2023-12-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_copies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='copies',
            field=models.IntegerField(default=1),
        ),
    ]
