# Generated by Django 5.0 on 2023-12-17 03:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='date_borrowed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
