# Generated by Django 5.0 on 2023-12-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0003_remove_borrowedbook_book_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='b_copies',
            field=models.IntegerField(default=1),
        ),
    ]
