# Generated by Django 5.0 on 2023-12-17 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0004_borrowedbook_b_copies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowedbook',
            old_name='b_book',
            new_name='borrowed_book',
        ),
        migrations.RenameField(
            model_name='borrowedbook',
            old_name='b_copies',
            new_name='borrowed_copies',
        ),
    ]
