# Generated by Django 5.0 on 2023-12-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0005_rename_b_book_borrowedbook_borrowed_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='status',
            field=models.CharField(default='N/A', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='borrowed_copies',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
