# Generated by Django 5.0 on 2023-12-17 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_copies'),
        ('borrower', '0006_borrowedbook_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='borrowed_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='borrowed_copies',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='status',
            field=models.CharField(default='N/A', max_length=30),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
